-- Up Migration

CREATE TABLE IF NOT EXISTS fabric_types (
  id       INTEGER      PRIMARY KEY,
  name     VARCHAR(100) NOT NULL,
  name_en  VARCHAR(100) NOT NULL,
  slug_de  VARCHAR(100) NOT NULL UNIQUE,
  slug_en  VARCHAR(100) NOT NULL UNIQUE,
  category VARCHAR(50)  NOT NULL,
  use_case VARCHAR(50)  NOT NULL
);

INSERT INTO fabric_types (id, name, name_en, slug_de, slug_en, category, use_case) VALUES
  (1, 'Baumwolle', 'Cotton', 'baumwolle', 'cotton', 'natural', 'apparel'),
  (2, 'Leinen', 'Linen', 'leinen', 'linen', 'natural', 'apparel'),
  (3, 'Seide', 'Silk', 'seide', 'silk', 'natural', 'apparel'),
  (4, 'Wolle', 'Wool', 'wolle', 'wool', 'natural', 'apparel'),
  (5, 'Kaschmir', 'Cashmere', 'kaschmir', 'cashmere', 'natural', 'apparel'),
  (6, 'Alpaka', 'Alpaca', 'alpaka', 'alpaca', 'natural', 'apparel'),
  (7, 'Mohair', 'Mohair', 'mohair', 'mohair', 'natural', 'apparel'),
  (8, 'Hanf', 'Hemp', 'hanf', 'hemp', 'natural', 'apparel'),
  (9, 'Jute', 'Jute', 'jute', 'jute', 'natural', 'upholstery'),
  (10, 'Bambus', 'Bamboo', 'bambus', 'bamboo', 'natural', 'apparel'),
  (11, 'Kokos', 'Coir', 'kokos', 'coir', 'natural', 'technical'),
  (12, 'Sisal', 'Sisal', 'sisal', 'sisal', 'natural', 'technical'),
  (13, 'Ramie', 'Ramie', 'ramie', 'ramie', 'natural', 'apparel'),
  (14, 'Angora', 'Angora', 'angora', 'angora', 'natural', 'apparel'),
  (15, 'Kamelhaar', 'Camel Hair', 'kamelhaar', 'camel-hair', 'natural', 'apparel'),
  (16, 'Schafschurwolle', 'Virgin Wool', 'schafschurwolle', 'virgin-wool', 'natural', 'apparel'),
  (17, 'Merino', 'Merino Wool', 'merino', 'merino', 'natural', 'apparel'),
  (18, 'Lammwolle', 'Lambswool', 'lammwolle', 'lambswool', 'natural', 'apparel'),
  (19, 'Filz', 'Felt', 'filz', 'felt', 'natural', 'craft'),
  (20, 'Kork', 'Cork Fabric', 'kork', 'cork', 'natural', 'accessories'),
  (21, 'Viskose', 'Viscose / Rayon', 'viskose', 'viscose', 'semi-synthetic', 'apparel'),
  (22, 'Modal', 'Modal', 'modal', 'modal', 'semi-synthetic', 'apparel'),
  (23, 'Lyocell / Tencel', 'Lyocell / Tencel', 'lyocell', 'lyocell', 'semi-synthetic', 'apparel'),
  (24, 'Acetat', 'Acetate', 'acetat', 'acetate', 'semi-synthetic', 'apparel'),
  (25, 'Triacetat', 'Triacetate', 'triacetat', 'triacetate', 'semi-synthetic', 'apparel'),
  (26, 'Cupro', 'Cupro', 'cupro', 'cupro', 'semi-synthetic', 'apparel'),
  (27, 'Polyester', 'Polyester', 'polyester', 'polyester', 'synthetic', 'apparel'),
  (28, 'Polyamid / Nylon', 'Polyamide / Nylon', 'polyamid', 'polyamide', 'synthetic', 'apparel'),
  (29, 'Acryl', 'Acrylic', 'acryl', 'acrylic', 'synthetic', 'apparel'),
  (30, 'Elasthan / Spandex', 'Elastane / Spandex / Lycra', 'elasthan', 'elastane', 'synthetic', 'apparel'),
  (31, 'Polypropylen', 'Polypropylene', 'polypropylen', 'polypropylene', 'synthetic', 'technical'),
  (32, 'Polyethylen', 'Polyethylene', 'polyethylen', 'polyethylene', 'synthetic', 'technical'),
  (33, 'Aramid / Kevlar', 'Aramid / Kevlar', 'aramid', 'aramid', 'synthetic', 'technical'),
  (34, 'Mikrofaser', 'Microfibre', 'mikrofaser', 'microfibre', 'synthetic', 'apparel'),
  (35, 'Fleece', 'Fleece', 'fleece', 'fleece', 'synthetic', 'apparel'),
  (36, 'Softshell', 'Softshell', 'softshell', 'softshell', 'synthetic', 'apparel'),
  (37, 'Neopren', 'Neoprene', 'neopren', 'neoprene', 'synthetic', 'apparel'),
  (38, 'PVC-Gewebe', 'PVC Fabric', 'pvc-gewebe', 'pvc-fabric', 'synthetic', 'technical'),
  (39, 'Mesh / Netzstoff', 'Mesh', 'mesh', 'mesh', 'synthetic', 'apparel'),
  (40, 'Tüll', 'Tulle', 'tuell', 'tulle', 'synthetic', 'apparel'),
  (41, 'Denim', 'Denim', 'denim', 'denim', 'woven', 'apparel'),
  (42, 'Tweed', 'Tweed', 'tweed', 'tweed', 'woven', 'apparel'),
  (43, 'Twill', 'Twill', 'twill', 'twill', 'woven', 'apparel'),
  (44, 'Satin', 'Satin', 'satin', 'satin', 'woven', 'apparel'),
  (45, 'Chiffon', 'Chiffon', 'chiffon', 'chiffon', 'woven', 'apparel'),
  (46, 'Organza', 'Organza', 'organza', 'organza', 'woven', 'apparel'),
  (47, 'Taft', 'Taffeta', 'taft', 'taffeta', 'woven', 'apparel'),
  (48, 'Popeline', 'Poplin', 'popeline', 'poplin', 'woven', 'apparel'),
  (49, 'Gabardine', 'Gabardine', 'gabardine', 'gabardine', 'woven', 'apparel'),
  (50, 'Flanell', 'Flannel', 'flanell', 'flannel', 'woven', 'apparel'),
  (51, 'Musselin', 'Muslin / Cheesecloth', 'musselin', 'muslin', 'woven', 'apparel'),
  (52, 'Batist', 'Batiste / Lawn', 'batist', 'batiste', 'woven', 'apparel'),
  (53, 'Canvas / Segeltuch', 'Canvas', 'canvas', 'canvas', 'woven', 'upholstery'),
  (54, 'Oxford-Stoff', 'Oxford Cloth', 'oxford-stoff', 'oxford-cloth', 'woven', 'apparel'),
  (55, 'Cord', 'Corduroy', 'cord', 'corduroy', 'woven', 'apparel'),
  (56, 'Brokat', 'Brocade', 'brokat', 'brocade', 'woven', 'apparel'),
  (57, 'Damast', 'Damask', 'damast', 'damask', 'woven', 'upholstery'),
  (58, 'Jacquard', 'Jacquard', 'jacquard', 'jacquard', 'woven', 'apparel'),
  (59, 'Voile', 'Voile', 'voile', 'voile', 'woven', 'apparel'),
  (60, 'Chambray', 'Chambray', 'chambray', 'chambray', 'woven', 'apparel'),
  (61, 'Jersey', 'Jersey', 'jersey', 'jersey', 'knit', 'apparel'),
  (62, 'Interlock', 'Interlock', 'interlock', 'interlock', 'knit', 'apparel'),
  (63, 'Rippenstrick', 'Ribbing', 'rippenstrick', 'ribbing', 'knit', 'apparel'),
  (64, 'Sweatshirt-Stoff', 'Sweatshirt Fabric', 'sweatshirt-stoff', 'sweatshirt-fabric', 'knit', 'apparel'),
  (65, 'Frottee', 'Terry / Towelling', 'frottee', 'terry', 'knit', 'apparel'),
  (66, 'Velours', 'Velour', 'velours', 'velour', 'knit', 'apparel'),
  (67, 'Strickstoff', 'Knit Fabric', 'strickstoff', 'knit', 'knit', 'apparel'),
  (68, 'Ponté-Roma', 'Ponte Roma', 'ponte-roma', 'ponte-roma', 'knit', 'apparel'),
  (69, 'Scuba-Stoff', 'Scuba Fabric', 'scuba-stoff', 'scuba', 'knit', 'apparel'),
  (70, 'Samt', 'Velvet', 'samt', 'velvet', 'pile', 'apparel'),
  (71, 'Plüsch', 'Plush', 'pluesch', 'plush', 'pile', 'craft'),
  (72, 'Kunstfell', 'Faux Fur', 'kunstfell', 'faux-fur', 'pile', 'apparel'),
  (73, 'Shearling / Lammfell-Imitat', 'Sherpa / Shearling', 'shearling', 'shearling', 'pile', 'apparel'),
  (74, 'Spitze', 'Lace', 'spitze', 'lace', 'lace', 'apparel'),
  (75, 'Stickerei-Stoff', 'Embroidery Fabric', 'stickerei-stoff', 'embroidery-fabric', 'lace', 'apparel'),
  (76, 'Guipure', 'Guipure Lace', 'guipure', 'guipure', 'lace', 'apparel'),
  (77, 'Leder', 'Leather', 'leder', 'leather', 'leather', 'apparel'),
  (78, 'Wildleder', 'Suede', 'wildleder', 'suede', 'leather', 'apparel'),
  (79, 'Kunstleder', 'Faux Leather / PU Leather', 'kunstleder', 'faux-leather', 'leather', 'apparel'),
  (80, 'Veganes Leder', 'Vegan Leather', 'veganes-leder', 'vegan-leather', 'leather', 'accessories'),
  (81, 'Vliesstoff', 'Nonwoven Fabric', 'vliesstoff', 'nonwoven', 'nonwoven', 'technical'),
  (82, 'Einlagestoff / Interfacing', 'Interfacing / Interlining', 'einlagestoff', 'interfacing', 'nonwoven', 'technical'),
  (83, 'Wattierung / Volumenvlies', 'Wadding / Batting', 'wattierung', 'wadding', 'nonwoven', 'craft'),
  (84, 'Glasfaser', 'Fibreglass Fabric', 'glasfaser', 'fibreglass', 'technical', 'technical'),
  (85, 'Carbonfaser', 'Carbon Fibre Fabric', 'carbonfaser', 'carbon-fibre', 'technical', 'technical'),
  (86, 'Chenille', 'Chenille', 'chenille', 'chenille', 'woven', 'upholstery'),
  (87, 'Gobelin', 'Tapestry / Gobelin', 'gobelin', 'tapestry', 'woven', 'upholstery'),
  (88, 'Bouclé', 'Boucle', 'boucle', 'boucle', 'woven', 'upholstery'),
  (89, 'Möbelstoff', 'Upholstery Fabric', 'moebelstoff', 'upholstery-fabric', 'woven', 'upholstery'),
  (90, 'Patchworkstoff', 'Quilting Fabric', 'patchworkstoff', 'quilting-fabric', 'woven', 'craft'),
  (91, 'Wachstuch', 'Oilcloth / Waxed Fabric', 'wachstuch', 'oilcloth', 'coated', 'craft'),
  (92, 'Gewachste Baumwolle', 'Waxed Cotton', 'gewachste-baumwolle', 'waxed-cotton', 'coated', 'apparel'),
  (93, 'Laminierter Stoff', 'Laminated Fabric', 'laminierter-stoff', 'laminated-fabric', 'coated', 'apparel');

-- Replace type column with fabric_type_id foreign key
ALTER TABLE fabrics DROP COLUMN type;
ALTER TABLE fabrics ADD COLUMN fabric_type_id INTEGER NOT NULL REFERENCES fabric_types(id);

-- Down Migration
